# Generated by Django 2.2.3 on 2019-07-21 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainedModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='fashionfile',
            name='type',
            field=models.CharField(choices=[('0', 'T-shirt/top'), ('1', 'Trouser'), ('2', 'Pullover'), ('3', 'Dress'), ('4', 'Coat'), ('5', 'Sandal'), ('6', 'Shirt'), ('7', 'Sneaker'), ('8', 'Bag'), ('9', 'Ankle boot')], max_length=200),
        ),
    ]
