# Generated by Django 2.2.3 on 2019-07-21 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0002_auto_20190721_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fashionfile',
            name='type',
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('0', 'T-shirt/top'), ('1', 'Trouser'), ('2', 'Pullover'), ('3', 'Dress'), ('4', 'Coat'), ('5', 'Sandal'), ('6', 'Shirt'), ('7', 'Sneaker'), ('8', 'Bag'), ('9', 'Ankle boot')], max_length=200)),
                ('fashion_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fashion.FashionFile')),
                ('trained_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fashion.TrainedModel')),
            ],
        ),
    ]
